/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description E2E health: Postgres reachable+migrated, Redis PING, Qdrant collection + vector dim.
         *
         *     Full diagnostic — any dependency error yields 503. Use /health/live and
         *     /health/ready for orchestrator probes; this endpoint is for monitoring
         *     dashboards and post-deploy verification.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Liveness probe: the process answers. Never touches dependencies, so a
         *     dependency outage can't make an orchestrator restart-loop the API.
         */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Readiness probe: Postgres (reachable + migrated) is required — without it
         *     every endpoint fails. Redis/Qdrant errors only mark the instance degraded:
         *     search falls back to keyword-only, so evicting the pod would lose capacity
         *     for no gain.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Public self-service signup: create a new organization, make the caller
         *     its org_admin, and log them straight in with the standard session cookie.
         *
         *     Email verification is intentionally not implemented yet — accounts are
         *     active on creation. See atip_api/services/auth.py for the extension notes.
         */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the presented session (idempotent: no error without one).
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Workspaces
         * @description Only workspaces the caller can read: their memberships, or all
         *     organization workspaces for org admins.
         */
        get: operations["list_workspaces_api_workspaces_get"];
        put?: never;
        /**
         * Create Workspace
         * @description Creates the workspace in the caller's organization; the caller becomes
         *     a workspace editor.
         */
        post: operations["create_workspace_api_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace */
        get: operations["get_workspace_api_workspaces__workspace_id__get"];
        put?: never;
        post?: never;
        /** Delete Workspace */
        delete: operations["delete_workspace_api_workspaces__workspace_id__delete"];
        options?: never;
        head?: never;
        /** Rename Workspace */
        patch: operations["rename_workspace_api_workspaces__workspace_id__patch"];
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_workspaces__workspace_id__documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description Accepts the file, records a PENDING job, and hands processing to the
         *     queue worker (202: poll GET /api/jobs/{job_id} for progress). If the queue
         *     is disabled or unreachable, processing falls back to an in-process task.
         */
        post: operations["upload_document_api_workspaces__workspace_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document File */
        get: operations["get_document_file_api_documents__document_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search Workspace
         * @description Hybrid retrieval: Postgres FTS + Qdrant semantic search fused with RRF.
         */
        post: operations["search_workspace_api_workspaces__workspace_id__search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Workspace
         * @description Verified RAG: hybrid retrieval + LLM answer checked against the retrieved chunks.
         */
        post: operations["ask_workspace_api_workspaces__workspace_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chat Workspace
         * @description Verified RAG over SSE: `sources`, then `token`*, then `final` — or `error`.
         *
         *     Auth: EventSource sends the session cookie same-origin, so this GET is
         *     protected exactly like the JSON routes. Streamed tokens are the unverified
         *     draft; the `final` event carries the verified answer and citations and
         *     must replace the streamed text.
         */
        get: operations["chat_workspace_api_workspaces__workspace_id__chat_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/evidence/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Evidence
         * @description Extract verified requirements. Unreviewed prior items are replaced;
         *     items with review state or history are archived, never deleted.
         */
        post: operations["extract_evidence_api_documents__document_id__evidence_extract_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_workspaces__workspace_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description Paginated review queue; archived items are excluded unless requested.
         *
         *     Tenant isolation: with a workspace_id the caller must be able to read that
         *     workspace; without one, results are restricted to the caller's readable
         *     workspaces.
         */
        get: operations["review_queue_api_evidence_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Evidence Item */
        get: operations["get_evidence_item_api_evidence__item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Evidence Item */
        patch: operations["update_evidence_item_api_evidence__item_id__patch"];
        trace?: never;
    };
    "/api/evidence/{item_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Evidence Item
         * @description Apply one audited review action; invalid transitions return 409.
         */
        post: operations["review_evidence_item_api_evidence__item_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{item_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evidence Item History
         * @description Full append-only audit trail of the item, oldest first.
         */
        get: operations["evidence_item_history_api_evidence__item_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/evidence/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Evidence Json */
        get: operations["export_evidence_json_api_workspaces__workspace_id__evidence_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspaces/{workspace_id}/evidence/export.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Evidence Markdown */
        get: operations["export_evidence_markdown_api_workspaces__workspace_id__evidence_export_md_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActorType
         * @enum {string}
         */
        ActorType: "HUMAN" | "SYSTEM";
        /** AnswerVerification */
        AnswerVerification: {
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "partial" | "unsupported" | "not_found";
            /** Claims Total */
            claims_total: number;
            /** Claims Validated */
            claims_validated: number;
            /** Citations Dropped */
            citations_dropped: number;
            /** Warnings */
            warnings: string[];
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /** Document Id */
            document_id?: string | null;
            /**
             * Top K
             * @default 8
             */
            top_k: number;
        };
        /** AskResponse */
        AskResponse: {
            /** Question */
            question: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Document Id */
            document_id: string | null;
            /** Answer Md */
            answer_md: string;
            /** Not Found */
            not_found: boolean;
            /** Confidence */
            confidence: number | null;
            /** Citations */
            citations: components["schemas"]["Citation"][];
            verification: components["schemas"]["AnswerVerification"];
            /** Sources */
            sources: components["schemas"]["RetrievedSourceRead"][];
            /** Semantic Used */
            semantic_used: boolean;
            /** Model */
            model: string;
        };
        /** Body_upload_document_api_workspaces__workspace_id__documents_post */
        Body_upload_document_api_workspaces__workspace_id__documents_post: {
            /** File */
            file: string;
        };
        /**
         * Citation
         * @description A verified citation; `citation_id` matches inline [n] markers in the answer.
         */
        Citation: {
            /** Citation Id */
            citation_id: number;
            /**
             * Postgres Chunk Id
             * Format: uuid
             */
            postgres_chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Clause Id */
            clause_id: string | null;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Source Text Snippet */
            source_text_snippet: string;
            /**
             * Status
             * @enum {string}
             */
            status: "validated" | "weak";
        };
        /** DocumentRead */
        DocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Name */
            name: string;
            status: components["schemas"]["DocumentStatus"];
            /** Sha256 */
            sha256: string | null;
            /** Page Count */
            page_count: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DocumentStatus
         * @enum {string}
         */
        DocumentStatus: "PENDING" | "PROCESSING" | "READY" | "FAILED";
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            document: components["schemas"]["DocumentRead"];
            job: components["schemas"]["JobRead"];
        };
        /** EvidenceCitationRead */
        EvidenceCitationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /** Clause Id */
            clause_id: string | null;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Quote */
            quote: string;
        };
        /** EvidenceExtractResponse */
        EvidenceExtractResponse: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Items */
            items: components["schemas"]["EvidenceItemRead"][];
            /** Requirements Seen */
            requirements_seen: number;
            /** Requirements Dropped */
            requirements_dropped: number;
            /** Citations Dropped */
            citations_dropped: number;
            /** Items Archived */
            items_archived: number;
            /** Warnings */
            warnings: string[];
            /** Model */
            model: string;
        };
        /** EvidenceItemDetail */
        EvidenceItemDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Requirement Text */
            requirement_text: string;
            status: components["schemas"]["EvidenceStatus"];
            risk: components["schemas"]["EvidenceRisk"];
            review_status: components["schemas"]["ReviewStatus"];
            /** Archived At */
            archived_at: string | null;
            /** Version */
            version: number;
            /** Citations */
            citations: components["schemas"]["EvidenceCitationRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Event Count */
            event_count: number;
            last_event: components["schemas"]["ReviewEventRead"] | null;
        };
        /** EvidenceItemExport */
        EvidenceItemExport: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Requirement Text */
            requirement_text: string;
            status: components["schemas"]["EvidenceStatus"];
            risk: components["schemas"]["EvidenceRisk"];
            review_status: components["schemas"]["ReviewStatus"];
            /** Archived At */
            archived_at: string | null;
            /** Version */
            version: number;
            /** Citations */
            citations: components["schemas"]["EvidenceCitationRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** History */
            history?: components["schemas"]["ReviewEventRead"][] | null;
        };
        /** EvidenceItemRead */
        EvidenceItemRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Requirement Text */
            requirement_text: string;
            status: components["schemas"]["EvidenceStatus"];
            risk: components["schemas"]["EvidenceRisk"];
            review_status: components["schemas"]["ReviewStatus"];
            /** Archived At */
            archived_at: string | null;
            /** Version */
            version: number;
            /** Citations */
            citations: components["schemas"]["EvidenceCitationRead"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EvidenceItemSummary
         * @description Queue row: enough metadata to render the Review Queue without citations.
         */
        EvidenceItemSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Requirement Text */
            requirement_text: string;
            status: components["schemas"]["EvidenceStatus"];
            risk: components["schemas"]["EvidenceRisk"];
            review_status: components["schemas"]["ReviewStatus"];
            /** Citation Count */
            citation_count: number;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EvidenceItemUpdate
         * @description Reviewer-owned inline edits (Phase 4 table); at least one must be provided.
         *
         *     These edits are audited: each change appends a review event. The workflow
         *     `review_status` cannot be changed here — use the review endpoint.
         */
        EvidenceItemUpdate: {
            status?: components["schemas"]["EvidenceStatus"] | null;
            risk?: components["schemas"]["EvidenceRisk"] | null;
            /**
             * Actor Name
             * @default anonymous
             */
            actor_name: string;
            /** Expected Version */
            expected_version?: number | null;
        };
        /**
         * EvidenceMapExport
         * @description JSON Evidence Map export; the Markdown export renders the same items.
         */
        EvidenceMapExport: {
            /** Workspace Id */
            workspace_id: string | null;
            /** Workspace Name */
            workspace_name: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Include History
             * @default false
             */
            include_history: boolean;
            /** Items */
            items: components["schemas"]["EvidenceItemExport"][];
        };
        /** EvidenceQueuePage */
        EvidenceQueuePage: {
            /** Items */
            items: components["schemas"]["EvidenceItemSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * EvidenceRisk
         * @description Reviewer-owned risk rating of an extracted requirement.
         * @enum {string}
         */
        EvidenceRisk: "UNRATED" | "LOW" | "MEDIUM" | "HIGH";
        /**
         * EvidenceStatus
         * @description Reviewer-owned compliance status of an extracted requirement.
         * @enum {string}
         */
        EvidenceStatus: "OPEN" | "IN_REVIEW" | "COMPLIANT" | "NON_COMPLIANT" | "NOT_APPLICABLE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"];
            };
            /** Generation Enabled */
            generation_enabled: boolean;
        };
        /** JobRead */
        JobRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            status: components["schemas"]["JobStatus"];
            /** Stage */
            stage: string | null;
            /** Attempts */
            attempts: number;
            /** Request Id */
            request_id: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "PENDING" | "PROCESSING" | "READY" | "FAILED";
        /**
         * LivenessResponse
         * @description Process is up. No dependency checks — safe for orchestrator liveness probes.
         */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /** Environment */
            environment: string;
            /** Build Sha */
            build_sha?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** OrganizationRead */
        OrganizationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * ReadinessResponse
         * @description Can serve traffic. Postgres is required; Redis/Qdrant outages only degrade
         *     (keyword-only search keeps working), so they must not evict the instance.
         */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded" | "not_ready";
            /** Services */
            services: {
                [key: string]: components["schemas"]["ServiceStatus"];
            };
        };
        /**
         * RegisterRequest
         * @description Public self-service signup. The registrant names their organization and
         *     becomes its ORG_ADMIN (see atip_api.services.auth).
         */
        RegisterRequest: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Organization Name */
            organization_name: string;
            /** Password */
            password: string;
        };
        /**
         * RetrievedSourceRead
         * @description A retrieved chunk as numbered in the prompt; streamed before generation.
         */
        RetrievedSourceRead: {
            /** Index */
            index: number;
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Document Name */
            document_name: string;
            /** Clause Id */
            clause_id: string | null;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
        };
        /**
         * ReviewAction
         * @description Actions recorded in the append-only review audit trail.
         * @enum {string}
         */
        ReviewAction: "START_REVIEW" | "APPROVE" | "REJECT" | "REQUEST_REVISION" | "COMMENT" | "SET_RISK" | "SET_STATUS" | "EXTRACTION_ARCHIVED";
        /** ReviewEventRead */
        ReviewEventRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Evidence Item Id
             * Format: uuid
             */
            evidence_item_id: string;
            action: components["schemas"]["ReviewAction"];
            previous_status: components["schemas"]["ReviewStatus"];
            next_status: components["schemas"]["ReviewStatus"];
            previous_risk: components["schemas"]["EvidenceRisk"];
            next_risk: components["schemas"]["EvidenceRisk"];
            /** Comment */
            comment: string | null;
            /** Actor Name */
            actor_name: string;
            actor_type: components["schemas"]["ActorType"];
            /** Extra */
            extra: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "START_REVIEW" | "APPROVE" | "REJECT" | "REQUEST_REVISION" | "COMMENT" | "SET_RISK";
            /** Actor Name */
            actor_name: string;
            actor_type: components["schemas"]["ActorType"];
            /** Comment */
            comment?: string | null;
            risk?: components["schemas"]["EvidenceRisk"] | null;
            /** Expected Version */
            expected_version?: number | null;
        };
        /** ReviewResponse */
        ReviewResponse: {
            item: components["schemas"]["EvidenceItemRead"];
            event: components["schemas"]["ReviewEventRead"];
        };
        /**
         * ReviewStatus
         * @description Workflow state of the human review of an extracted evidence item.
         *
         *     Orthogonal to EvidenceStatus (compliance verdict): this tracks whether a
         *     human has reviewed the extraction itself.
         * @enum {string}
         */
        ReviewStatus: "NEW" | "IN_REVIEW" | "APPROVED" | "REJECTED" | "NEEDS_REVISION";
        /** SearchRequest */
        SearchRequest: {
            /** Query */
            query: string;
            /** Document Id */
            document_id?: string | null;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Document Id */
            document_id: string | null;
            /** Top K */
            top_k: number;
            /** Semantic Used */
            semantic_used: boolean;
            /**
             * Rerank Used
             * @default false
             */
            rerank_used: boolean;
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Workspace Id
             * Format: uuid
             */
            workspace_id: string;
            /** Version Id */
            version_id?: string | null;
            /** Document Name */
            document_name: string;
            /** Chunk Index */
            chunk_index: number;
            /** Page Start */
            page_start: number;
            /** Page End */
            page_end: number;
            /** Clause Id */
            clause_id: string | null;
            /** Heading */
            heading: string | null;
            /** Section Path */
            section_path?: string | null;
            /** Text */
            text: string;
            scores: components["schemas"]["SearchScores"];
        };
        /**
         * SearchScores
         * @description Rank/score breakdown per retrieval leg plus the fused RRF score.
         */
        SearchScores: {
            /** Rrf */
            rrf: number;
            /** Keyword Rank */
            keyword_rank?: number | null;
            /** Keyword Score */
            keyword_score?: number | null;
            /** Semantic Rank */
            semantic_rank?: number | null;
            /** Semantic Score */
            semantic_score?: number | null;
            /** Rerank Rank */
            rerank_rank?: number | null;
            /** Rerank Score */
            rerank_score?: number | null;
        };
        /** ServiceStatus */
        ServiceStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Detail */
            detail?: string | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["UserRole"];
            organization: components["schemas"]["OrganizationRead"];
        };
        /**
         * UserRole
         * @description Account-level role. Workspace-level rights live on WorkspaceMember.
         * @enum {string}
         */
        UserRole: "PLATFORM_ADMIN" | "ORG_ADMIN" | "MEMBER";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceCreate */
        WorkspaceCreate: {
            /** Name */
            name: string;
        };
        /** WorkspaceRead */
        WorkspaceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** WorkspaceUpdate */
        WorkspaceUpdate: {
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_workspaces_api_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRead"][];
                };
            };
        };
    };
    create_workspace_api_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workspace_api_workspaces__workspace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workspace_api_workspaces__workspace_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_workspace_api_workspaces__workspace_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_workspaces__workspace_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_workspaces__workspace_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_workspaces__workspace_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_file_api_documents__document_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_workspace_api_workspaces__workspace_id__search_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_workspace_api_workspaces__workspace_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_workspace_api_workspaces__workspace_id__chat_get: {
        parameters: {
            query: {
                question: string;
                document_id?: string | null;
                top_k?: number;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    extract_evidence_api_documents__document_id__evidence_extract_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceExtractResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_workspaces__workspace_id__evidence_get: {
        parameters: {
            query?: {
                document_id?: string | null;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceItemRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_api_evidence_review_queue_get: {
        parameters: {
            query?: {
                workspace_id?: string | null;
                document_id?: string | null;
                review_status?: components["schemas"]["ReviewStatus"] | null;
                risk?: components["schemas"]["EvidenceRisk"] | null;
                include_archived?: boolean;
                sort?: "updated_desc" | "updated_asc" | "created_desc" | "created_asc" | "risk_desc" | "risk_asc";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceQueuePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_item_api_evidence__item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceItemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_evidence_item_api_evidence__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceItemUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceItemRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_evidence_item_api_evidence__item_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_item_history_api_evidence__item_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_evidence_json_api_workspaces__workspace_id__evidence_export_get: {
        parameters: {
            query?: {
                document_id?: string | null;
                review_status?: components["schemas"]["ReviewStatus"] | null;
                risk?: components["schemas"]["EvidenceRisk"] | null;
                include_history?: boolean;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceMapExport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_evidence_markdown_api_workspaces__workspace_id__evidence_export_md_get: {
        parameters: {
            query?: {
                document_id?: string | null;
                review_status?: components["schemas"]["ReviewStatus"] | null;
                risk?: components["schemas"]["EvidenceRisk"] | null;
                include_history?: boolean;
            };
            header?: never;
            path: {
                workspace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                    "text/markdown": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
